### PR TITLE
Website template

### PR DESCRIPTION
**Pull request by erickyvand**
### What does this PR do?
- Creates a website template
### How to test it manually?
- clone this repository
- cd to the cloned folder
- change the branch to `ft-create-template`
- in the template folder open `index.html` with `live server extension` (Note: install it, if you don't have it installed)
# Screenshots

Screenshot from 2021-01-26 15-17-02
Screenshot from 2021-01-26 15-17-39
Screenshot from 2021-01-26 15-18-13
Screenshot from 2021-01-26 15-18-48
Screenshot from 2021-01-26 15-19-22

### CODE REVIEW

**Comment by fridolinho** [comment]
Hello @erickyvand please share how can we test this?

**Comment by erickyvand** [comment]
@fridolinho check the PR description I have updated it.

**Comment by fridolinho** [comment]
1. add social icons, phone and whatsapp icon to left side of contact session
2. push contact form the right
3. center the header menu for each section with media query for big screen (laptop and desktop)
4. replace existing social icon with a call to action button (Contact us)
5. Navigation menu for mobile (dropdown with a humburger Menu)

**Comment by patrickngabo** [comment]
- Letters are not readable with that hotel background
 - Titles on each section should be moved down a little. i.e: Know about us shouldn't touch that black line on top and also it would be better if they are centered.

**Comment by fridolinho** [comment]
1. Add block of contact details(dynamic email and phone)
- email icon: info@template.rw
- Phone icon: 0788232369
2. make social link dynamic
3. services slider one by one(remember to add a title)
4. add logo (image shared on slack)

**Pull request merged**
