### PR TITLE
editing template to freshopenminds.rw website

### PR DESCRIPTION
**Pull request by emmymbaraga**
what is this PR does?
-editing script and using a single image instead of slide one in top section.
-Insert favicon logo and Change title in index.html.
-Change footer text in footer.html.
-Modify images array buy including images for a specific company.
-including information for Fresh open minds'  company.
-Changing the background color.

### CODE REVIEW

**Comment by fridolinho** [comment]
Hello @emmymbaraga please delete the template and template1 folders.

**Comment by fridolinho** [comment]
image
please remove the highlighted text the short description must be 1  paragraph or 2 when there is not many words.

**Comment by fridolinho** [comment]
image
split these texts into 2 paragraphs and use them under mission and vision but hide the titles(Mission, mission)

**Comment by fridolinho** [comment]
set the logo image width to 50 and use this image as logo
logo

**Review by emmymbaraga — COMMENTED** [review]
what is this PR does?
-removing the text in order to have the short description must be 1 paragraph or 2 when there is not many words.
-split these texts into 2 paragraphs and use them under mission and vision but hide the titles(Mission, mission).
-set the logo image width to 50 and use another image as a logo

**Review by fridolinho — APPROVED** [review]

**Pull request closed without merging**
